name: Cập nhật tên miền 
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run:
    name: Cập nhật tên miền 
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
          
      - name: Cập nhật tên miền 
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV
        
      - name: Commit tool 
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'dnr-lang-vi.json'
          default_author: github_actor 
          message: 'Cập nhật tên miền: ${{ env.DATE }}'
          push: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
